import React from 'react';
import './Terms.css';

const Terms = () => {
  return (
    <div className="terms-page">
      <section className="terms-hero">
        <div className="terms-hero-content">
          <h1>Terms of Service</h1>
          <p>Last updated: January 2, 2026</p>
        </div>
      </section>

      <section className="terms-content">
        <div className="terms-container">
          <div className="terms-text">
            <p>
              Welcome to FewInfos, a student-run organization founded and operated by dedicated students who are passionate about technology, innovation, and providing valuable services to the community. By accessing, browsing, or using any of the services, products, features, or content provided by FewInfos through our website, applications, platforms, or any other digital or physical means, you expressly acknowledge, accept, and agree to be legally bound by all the terms, conditions, provisions, obligations, and stipulations outlined in this comprehensive Terms of Service agreement. This document constitutes a binding legal contract between you, as the user or client, and FewInfos, as the service provider and student organization. If you do not agree with any part of these Terms of Service, or if you have reservations about any provisions contained herein, you must immediately discontinue your use of our services and refrain from accessing our website or engaging with our offerings. Your continued use of our services after reviewing these terms signifies your complete acceptance and understanding of this agreement.
            </p>
            <p>
              FewInfos is proudly operated entirely by students who are currently pursuing their academic education while simultaneously building practical, real-world experience in technology, business management, project delivery, customer service, and entrepreneurship. Our student team members are committed to upholding professional standards and delivering high-quality services despite the unique challenges and constraints that come with balancing academic responsibilities and business operations. We believe that our student-run nature is one of our greatest strengths, bringing fresh perspectives, innovative approaches, cutting-edge knowledge from current academic research, enthusiasm, adaptability, and a genuine commitment to learning and improvement. However, we also recognize that being managed by students means our organization operates within certain limitations, including availability during academic terms, examination periods, holidays, and academic breaks, as well as potential adjustments to service delivery timelines during peak academic seasons.
            </p>
            <p>
              By agreeing to these Terms of Service, you acknowledge and understand that FewInfos is a student initiative, and while we strive for excellence and professionalism in all our endeavors, there may be occasional delays, scheduling adjustments, or service modifications necessitated by our academic commitments, educational requirements, examinations, thesis work, internship obligations, or other student-related circumstances. We commit to communicating any such situations transparently and working with you to find suitable solutions that minimize any inconvenience while respecting both your needs and our academic responsibilities. Our dedication to providing quality services remains unwavering, and we view every project as an opportunity to apply our academic learning, develop professional skills, and contribute meaningful value to our clients and community.
            </p>
            <p>
              Permission is hereby granted to you as a user to temporarily access and view the materials, information, content, software, documentation, resources, and other elements available on FewInfos' website and digital platforms for personal, educational, informational, or non-commercial purposes only. This grant constitutes a limited, revocable, non-exclusive, non-transferable license to use our materials and does not represent or imply any transfer of title, ownership rights, intellectual property, or proprietary interests in any content, software, or materials provided by FewInfos. Under the terms of this license, you explicitly agree that you may not modify, copy, reproduce, duplicate, distribute, or create derivative works from any materials without prior written authorization from our student management team. You are prohibited from using our materials for any commercial purpose, public display, redistribution, resale, or exploitation without explicit permission.
            </p>
            <p>
              You may not attempt to decompile, reverse engineer, disassemble, or extract source code from any software, applications, tools, or proprietary technology contained on or provided through FewInfos' website or services. You agree not to remove, obscure, alter, or tamper with any copyright notices, trademark attributions, proprietary legends, watermarks, or other intellectual property identifiers from any materials, content, or software. You are forbidden from transferring, sublicensing, selling, renting, or lending the materials to any other person, organization, or entity, and you may not mirror, replicate, cache, or host the materials on any other server, platform, or distribution network without our express written consent. This license shall automatically and immediately terminate if you violate any of these restrictions, limitations, or conditions, and may be terminated by FewInfos at any time, with or without notice, at our sole discretion. Upon termination of this license, you must immediately cease all use of the materials and destroy any copies in your possession or control.
            </p>
            <p>
              FewInfos provides a comprehensive range of technology solutions, consulting services, software development, web design and development, mobile application creation, digital marketing support, educational resources, training workshops, event management, product sales, course offerings, technical support, and various other related services as described on our website and promotional materials. The specific nature, scope, deliverables, timeline, and characteristics of services may vary depending on the particular offering, client requirements, project specifications, and current capabilities of our student team. We reserve the absolute right to modify, update, enhance, suspend, discontinue, limit, or alter any aspect of our services, features, functionality, pricing, availability, or content at any time without prior notice or liability. This includes the right to add new services, remove existing offerings, change service specifications, update technological implementations, modify pricing structures, or adjust operational procedures as deemed necessary by our student management team to reflect our organizational growth, evolving capabilities, changing academic schedules, market conditions, technological advancements, resource availability, or strategic direction.
            </p>
            <p>
              As a user of FewInfos services, you expressly agree to fulfill certain obligations and responsibilities that are essential for maintaining a productive, respectful, legal, and professional relationship. You agree to provide accurate, complete, current, and truthful information when requested during account registration, service inquiries, project consultations, contact forms, surveys, or any other interaction with our organization. You understand that providing false, misleading, or incomplete information may result in service delays, project complications, or termination of services. You are responsible for maintaining the security and confidentiality of your account credentials, including usernames, passwords, authentication codes, and any other access information, and you agree to notify us immediately of any unauthorized use, security breach, or suspected compromise of your account.
            </p>
            <p>
              You agree not to use our services for any illegal, unauthorized, harmful, fraudulent, deceptive, threatening, harassing, defamatory, obscene, or otherwise objectionable purpose or activity. You will not violate any applicable local, state, national, or international laws, regulations, statutes, ordinances, or legal requirements in your jurisdiction, including but not limited to copyright laws, trademark regulations, privacy laws, data protection regulations, consumer protection statutes, or any other relevant legal framework. You agree not to transmit, upload, distribute, or otherwise make available any viruses, malware, trojans, worms, ransomware, spyware, or any other malicious code, harmful software, or destructive elements that could damage, interfere with, interrupt, compromise, or negatively affect our services, servers, networks, systems, or other users' devices and data. You will not engage in any conduct that interferes with, disrupts, degrades, or inhibits other users' ability to enjoy and utilize our services, and you will not attempt to gain unauthorized access to any systems, accounts, data, or resources that you are not explicitly authorized to access.
            </p>
            <p>
              All content, materials, features, functionality, technology, information, text, graphics, photographs, images, videos, audio, logos, trademarks, service marks, trade names, software code, applications, tools, designs, layouts, user interfaces, documentation, and any other intellectual property available on or through our website and services are the exclusive property of FewInfos, our student team members, or our licensed content providers, and are protected by applicable international, federal, state, and local copyright laws, trademark laws, patent laws, trade secret laws, and other intellectual property rights and unfair competition laws. The compilation, organization, arrangement, coordination, and collective presentation of all content on our website and services is also the exclusive property of FewInfos and is protected by copyright and other intellectual property laws. Nothing in these Terms of Service should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any intellectual property without our prior written permission or the permission of the respective rights holder. Unauthorized use of our intellectual property may constitute infringement and subject you to legal action, damages, and other remedies available under applicable law.
            </p>
            <p>
              For any paid services, products, courses, subscriptions, consulting engagements, or other fee-based offerings provided by FewInfos, you agree to pay all applicable fees, charges, costs, expenses, and any applicable taxes associated with your account, purchases, or service agreements according to the payment terms, schedules, and methods specified at the time of purchase or as outlined in separate service agreements, contracts, or invoices. All fees are stated in the currency specified on our website or invoices and are due according to the payment schedule indicated. Unless otherwise explicitly stated in a separate refund policy, written agreement, or as required by applicable consumer protection laws, all fees paid for services, products, or courses are generally non-refundable once services have commenced, products have been delivered, or access has been granted. This reflects the significant time, effort, resources, and student labor invested in preparing and delivering services, even if you choose not to fully utilize them.
            </p>
            <p>
              We reserve the right to change, adjust, modify, increase, or decrease our fees, pricing structures, payment terms, or billing methods at any time with reasonable advance notice provided through our website, email communications, account notifications, or other appropriate channels. Any price changes will apply to future purchases, renewals, or service periods and will not retroactively affect services already paid for under previous pricing terms. You are responsible for reviewing current pricing before making purchases or renewing services. In cases where payments are overdue, outstanding, or in default, we reserve the right to suspend or terminate access to services, withhold deliverables, charge late fees or interest as permitted by law, pursue collection efforts, or take other appropriate action to recover amounts owed. As a student organization with limited financial resources, timely payment is crucial to our ability to maintain operations, compensate student team members fairly for their work, cover operational expenses, invest in tools and technologies, and continue serving our community effectively.
            </p>
            <p>
              To the maximum extent permitted by applicable law, in no event shall FewInfos, its student founders, team members, officers, advisors, faculty sponsors, affiliated educational institutions, partners, suppliers, contractors, or any related parties be liable to you or any third party for any indirect, incidental, consequential, special, punitive, or exemplary damages whatsoever, including but not limited to damages for loss of profits, loss of data, loss of business opportunities, business interruption, loss of use, loss of goodwill, work stoppage, equipment failure, software malfunction, or any other commercial damages or losses arising out of or in any way connected with your use or inability to use our services, website, materials, content, or any information provided, even if FewInfos or an authorized representative has been advised, notified, or should have been aware of the possibility of such damages. Our total aggregate liability arising out of or relating to these Terms of Service, your use of our services, or any products or services purchased from us, whether based in contract, tort, negligence, strict liability, or any other legal theory, shall not exceed the total amount you have actually paid to FewInfos during the twelve months immediately preceding the event giving rise to the liability claim.
            </p>
            <p>
              This limitation of liability reflects the nature of FewInfos as a student-run organization operating with limited resources, the educational and developmental nature of our operations, the pricing of our services which may be significantly lower than comparable commercial providers, and the inherent uncertainties and learning aspects involved in student-led initiatives. You acknowledge and agree that these limitations of liability are reasonable given the circumstances and that you assume certain risks in choosing to work with a student organization. These limitations apply to all claims and causes of action regardless of the form of action or legal theory under which liability might be asserted.
            </p>
            <p>
              The materials, services, products, information, and content provided on FewInfos' website and through our various offerings are provided on an "as is" and "as available" basis without warranties, representations, or guarantees of any kind, either express or implied. FewInfos makes no warranties, expressed or implied, and hereby expressly disclaims and negates all warranties, representations, and conditions including, without limitation, any implied warranties or conditions of merchantability, fitness for a particular purpose, title, non-infringement of intellectual property, accuracy, completeness, reliability, quality, timeliness, security, or availability. We do not warrant that our services will be uninterrupted, error-free, secure, or free from viruses or other harmful components, or that defects will be corrected promptly or at all. We make no warranty regarding the quality, accuracy, reliability, completeness, currency, or validity of any content, information, advice, recommendations, or services provided through our website or by our student team members.
            </p>
            <p>
              As a student organization, we are continuously learning, experimenting, and developing our skills and capabilities. While we strive for excellence and professionalism in all our work, we cannot guarantee perfection or warrant that our services will meet all your specific requirements, expectations, or business needs. You acknowledge that certain services may be experimental, developmental, or educational in nature, and that student team members, despite their dedication and academic training, may have varying levels of practical experience. This disclaimer does not affect any warranties or guarantees that cannot be excluded or limited under applicable law, and you may have additional consumer rights that cannot be waived by this agreement.
            </p>
            <p>
              You agree to indemnify, defend, and hold completely harmless FewInfos, its student founders, team members, officers, directors, advisors, faculty sponsors, affiliated educational institutions, partners, suppliers, contractors, agents, employees, volunteers, and any other related parties from and against any and all losses, damages, liabilities, deficiencies, claims, demands, actions, judgments, settlements, interest, awards, penalties, fines, costs, expenses, or fees of whatever kind, including reasonable attorneys' fees, legal costs, and expenses, arising from or relating to your use or misuse of our services, website, or products, your violation of these Terms of Service or any applicable law or regulation, your violation of any third-party rights including intellectual property rights or privacy rights, any content or materials you submit or transmit through our services, any fraudulent, negligent, or willful misconduct on your part, or any disputes or issues between you and any third party. This indemnification obligation shall survive the termination or expiration of these Terms of Service and your use of our services.
            </p>
            <p>
              We may terminate or suspend your account, access to our services, and ability to use our website immediately, with or without prior notice or warning, without liability or obligation to provide refunds or explanations, for any reason whatsoever or for no reason at all, at our sole discretion and judgment. Grounds for termination may include, but are not limited to, any breach or violation of these Terms of Service or any other policies, guidelines, or agreements you have entered into with FewInfos, fraudulent or inappropriate behavior, failure to pay amounts owed, abuse of our services or resources, harassment of our student team members or other users, legal or regulatory concerns, security issues, or discontinuation of our services. Upon termination, your right to use our services will immediately cease, you will lose access to any accounts, content, or materials, and we may delete or disable your account and all associated information and files without liability. You may also choose to terminate your use of our services at any time by ceasing to access our website and notifying us of your intention to close your account.
            </p>
            <p>
              These Terms of Service shall be governed by and construed in accordance with the laws of the applicable jurisdiction in which FewInfos operates, without regard to its conflict of law provisions, principles, or rules that might otherwise refer determination of such matters to the laws of another jurisdiction. Any legal action, suit, or proceeding arising out of or relating to these Terms of Service or your use of our services must be instituted exclusively in the courts of the applicable jurisdiction, and you agree to submit to the personal jurisdiction of such courts and waive any objection to venue in such courts. Our failure to enforce any right, provision, or term of these Terms of Service will not be deemed a waiver of such right, provision, or future enforcement of that or any other term. If any provision of these Terms of Service is found by a court of competent jurisdiction to be invalid, illegal, or unenforceable, such provision shall be limited or eliminated to the minimum extent necessary so that these Terms of Service shall otherwise remain in full force and effect and enforceable.
            </p>
            <p>
              FewInfos reserves the right to modify, update, amend, or replace these Terms of Service at any time as our student organization evolves, as our services expand or change, as we learn and improve our practices, as legal requirements change, or as we deem necessary for operational, educational, or strategic reasons. Changes may be made to reflect new services or features, address legal developments, incorporate user feedback, respond to security concerns, or adapt to the changing nature of our student-run operations. If we make material changes that significantly affect your rights or obligations under these Terms of Service, we will provide reasonable notice through prominent announcements on our website, email notifications to registered users, or other appropriate communication channels. Material changes will typically become effective no sooner than thirty days after notice is provided, giving you adequate time to review and assess the changes. For non-material changes, corrections, or clarifications, updates may take effect immediately upon posting to our website. What constitutes a material change will be determined at our sole discretion based on the nature and impact of the modification. We encourage you to review these Terms of Service periodically, and we will indicate the date of the most recent update at the top of this document. Your continued access to or use of our services after any modifications become effective constitutes your binding acceptance of the revised Terms of Service. If you do not agree with any changes, your sole remedy is to discontinue using our services.
            </p>
            <p>
              If you have any questions, concerns, comments, suggestions, requests for clarification, complaints, or inquiries regarding these Terms of Service, our policies, our services, our student organization, or any other matter related to FewInfos, we sincerely welcome and encourage you to contact us. As a student-run organization, we value open communication, feedback, and dialogue with our users and clients, and we are committed to addressing your concerns promptly, professionally, and thoroughly to the best of our abilities. You can reach our student team by sending an email to fewinfos@gmail.com, where dedicated student representatives will review your message and respond as quickly as possible, typically within two to three business days, though response times may vary during examination periods, academic breaks, holidays, or periods of high volume. You may also contact us by telephone at +91 8122118540 during our operating hours, which are generally aligned with academic terms and schedules; please note that as a student organization, our phone availability may be limited and may not follow traditional business hours. Additionally, you can send written correspondence, formal notices, legal documents, or detailed inquiries by mail to Karur, TN, India, and we will respond appropriately to any correspondence received through postal service.
            </p>
            <p>
              We genuinely appreciate your interest in FewInfos, your trust in choosing to work with a student-run organization, and your understanding of the unique circumstances, challenges, and opportunities inherent in our operations. We are deeply committed to providing excellent services, delivering real value, maintaining professional standards, learning from every experience, continuously improving our processes and capabilities, and building meaningful relationships with our clients and community. Your feedback, patience, and support are invaluable to our growth and success as students developing our skills, building our experience, and working to make a positive impact through technology and innovation. By using our services and agreeing to these Terms of Service, you acknowledge that you have carefully read, thoroughly understood, and agree to be legally bound by all the terms, conditions, provisions, obligations, rights, and responsibilities outlined in this comprehensive agreement, and you confirm your understanding that FewInfos is a student-led initiative operated by dedicated students who are balancing academic pursuits with entrepreneurial endeavors.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Terms;
