import React from 'react';
import './Privacy.css';

const Privacy = () => {
  return (
    <div className="privacy-page">
      <section className="privacy-hero">
        <div className="privacy-hero-content">
          <h1>Privacy Policy</h1>
          <p>Last updated: January 2, 2026</p>
        </div>
      </section>

      <section className="privacy-content">
        <div className="privacy-container">
          <div className="privacy-text">
            <p>
              Welcome to FewInfos, a student-led initiative founded and operated by passionate students dedicated to empowering businesses with innovative technology solutions. As a student-run organization, we understand the importance of trust, transparency, and responsible data handling. We respect your privacy and are deeply committed to protecting your personal data with the same care and diligence we apply to our academic pursuits. This comprehensive privacy policy has been crafted to inform you about how we collect, use, store, and protect your personal information when you visit our website, engage with our services, or interact with our team. We want you to understand your privacy rights and how applicable data protection laws safeguard your information.
            </p>
            <p>
              FewInfos is managed and operated entirely by students who are pursuing their education while building real-world experience in technology, business, and service delivery. Our commitment to your privacy reflects our dedication to ethical practices and professional standards, even as we continue to learn and grow. We have implemented this privacy policy to ensure that every individual who interacts with our platform can do so with confidence, knowing that their personal information is handled responsibly and in accordance with established legal frameworks and best practices in data protection.
            </p>
            <p>
              In the course of providing our services, which include technology consulting, software development, educational resources, and innovative business solutions, we may collect, use, store, and transfer various types of personal data about you. The information we collect can be broadly categorized into several key areas. Identity data includes your first name, last name, username, student identification numbers where applicable, or any similar identifiers that help us recognize and communicate with you effectively. Contact data encompasses your email address, telephone numbers, physical mailing address, and any other communication channels you provide to us for correspondence and service delivery purposes.
            </p>
            <p>
              Technical data represents the digital footprint created when you interact with our website and online services. This includes your internet protocol (IP) address, which helps us understand your general geographic location and ensure security; your browser type and version, which allows us to optimize our website's compatibility and performance; time zone settings and location data that help us provide timely and relevant services; browser plug-in types and versions that affect how you experience our content; your operating system and platform information that guides our technical support efforts; and various other technical identifiers that help us maintain and improve our digital infrastructure. Usage data provides valuable insights into how you navigate and utilize our website, products, and services, including pages visited, features accessed, time spent on different sections, click patterns, and interaction preferences.
            </p>
            <p>
              Additionally, we gather marketing and communications data, which includes your preferences regarding receiving promotional materials, newsletters, updates about our student projects and initiatives, event invitations, and your communication preferences across different channels. We are transparent about the fact that as a student organization, we are continuously learning and adapting our practices. We may also collect feedback, testimonials, project-related information, and academic collaboration details when you participate in our initiatives or educational programs. All data collection is conducted with respect for your privacy and in compliance with applicable regulations, including considerations for educational institutions and student organizations.
            </p>
            <p>
              We use your personal data for multiple legitimate purposes that support both our operations and your experience with our services. Primarily, we use this information to provide, maintain, and improve our technology solutions and services, ensuring that you receive the quality and reliability you expect from us despite our student-run nature. We use your contact information to communicate with you about service updates, respond to your inquiries and support requests, notify you about changes to our policies or services, and keep you informed about new features, projects, or opportunities that may interest you. As students, we are particularly committed to providing excellent customer support and educational resources, and we use your information to facilitate these interactions effectively.
            </p>
            <p>
              Your data helps us gather valuable analysis and insights that enable us to enhance our services, understand user needs better, and develop new solutions that address real-world challenges. We monitor the usage of our services to identify trends, troubleshoot technical issues, optimize performance, and ensure that our platform remains secure and functional. Security and fraud prevention are paramount concerns, and we use technical data to detect, prevent, and address security incidents, unauthorized access attempts, and technical problems before they impact your experience. With your explicit consent, we may also send you marketing communications about our student initiatives, upcoming events, new services, educational workshops, collaboration opportunities, and other information we believe may be valuable to you. You always have the option to opt out of marketing communications while continuing to receive essential service-related updates.
            </p>
            <p>
              As a student-led organization, we also use aggregated and anonymized data for research and educational purposes, helping our team members learn about data analytics, user experience design, and business intelligence while ensuring individual privacy is maintained. We may share insights derived from this data in academic presentations, student competitions, or educational forums, but we never share personally identifiable information in these contexts without explicit permission. Your information may also be used to facilitate collaboration between our student team members, coordinate project deliveries, manage academic partnerships, and fulfill any contractual obligations we have undertaken with you or your organization.
            </p>
            <p>
              Data security is a critical priority for FewInfos, and despite being a student organization, we have implemented robust security measures to protect your personal data from being accidentally lost, accessed without authorization, used inappropriately, altered, disclosed improperly, or compromised in any way. We employ industry-standard encryption technologies, secure data storage solutions, access control mechanisms, and regular security audits to maintain the integrity and confidentiality of your information. Access to your personal data is strictly limited to student team members, advisors, and third-party service providers who have a legitimate business need to access this information for providing services to you. All individuals with access to personal data are bound by confidentiality obligations and are trained on proper data handling procedures.
            </p>
            <p>
              We regularly review and update our security practices to address emerging threats and incorporate the latest protective technologies available to us. As students, we take our responsibility seriously and consult with faculty advisors, industry mentors, and cybersecurity professionals to ensure our security measures meet or exceed standard requirements. We conduct periodic security assessments, maintain detailed logs of data access, implement multi-factor authentication where appropriate, and have established incident response protocols to address any potential security breaches promptly and effectively. While no system can guarantee absolute security, we are committed to maintaining the highest standards possible and continuously improving our security posture.
            </p>
            <p>
              Regarding data retention, we adhere to a principle of data minimization and responsible stewardship. We will only retain your personal data for as long as necessary to fulfill the specific purposes for which it was collected, including satisfying any legal, accounting, reporting, or academic requirements that may apply to our student organization. When determining appropriate retention periods, we consider the nature and sensitivity of the data, the purposes for which we process it, whether we can achieve those purposes through other means, and applicable legal requirements. Once your data is no longer needed, we securely delete or anonymize it in accordance with our data retention schedule and disposal procedures. You have the right to request deletion of your data at any time, subject to certain legal exceptions, and we will honor such requests promptly.
            </p>
            <p>
              Under applicable data protection laws and regulations, you have several important legal rights concerning your personal data, and we are committed to facilitating the exercise of these rights. You have the right to request access to your personal data, which means you can ask us to confirm whether we are processing your information and request a copy of the data we hold about you. You have the right to request correction of any inaccurate, incomplete, or outdated personal data we maintain, and we will update our records accordingly upon verification. You may request erasure of your personal data in certain circumstances, such as when it is no longer necessary for the purposes for which it was collected, when you withdraw consent upon which processing is based, or when you object to processing and there are no overriding legitimate grounds for continued processing.
            </p>
            <p>
              You have the right to object to processing of your personal data where we are relying on legitimate interests as our legal basis for processing, and you believe your fundamental rights and freedoms outweigh our legitimate interests. You can request restriction of processing your personal data in specific situations, such as when you contest the accuracy of the data, when the processing is unlawful but you prefer restriction over deletion, or when we no longer need the data but you require it for legal claims. You have the right to request transfer of your personal data to another service provider in a structured, commonly used, and machine-readable format where technically feasible. Most importantly, where we rely on your consent to process personal data, you have the right to withdraw that consent at any time, though this will not affect the lawfulness of processing conducted before withdrawal.
            </p>
            <p>
              Our website uses cookies and similar tracking technologies to enhance your browsing experience, remember your preferences, analyze site traffic, and improve our services. Cookies are small text files stored on your device that help us distinguish you from other users and provide you with a personalized experience. We use both session cookies, which expire when you close your browser, and persistent cookies, which remain on your device for a longer period. These cookies help us understand how visitors interact with our website, which pages are most popular, how users navigate through our site, and where improvements can be made. Some cookies are essential for basic website functionality, while others are used for analytics, personalization, and marketing purposes. You can control and manage cookies through your browser settings, though disabling certain cookies may affect your ability to use some features of our website. We respect your choices regarding cookies and provide clear information about how we use them.
            </p>
            <p>
              Our website and services may include links to third-party websites, platforms, plug-ins, applications, and external resources that are not operated or controlled by FewInfos or our student team. When you click on these external links or enable connections to third-party services, you may be directed away from our website to platforms operated by other organizations, companies, or individuals. These third parties may collect or share data about you according to their own privacy policies and practices, which may differ significantly from ours. We want to emphasize that we do not control, endorse, or assume responsibility for the privacy practices, content, or policies of any third-party websites or services. We strongly encourage you to review the privacy policies and terms of service of any external site you visit or service you use. As a student organization, we strive to partner with reputable third-party providers, but we cannot guarantee or be held liable for their data handling practices.
            </p>
            <p>
              FewInfos reserves the right to modify, update, or replace this Privacy Policy at any time as our services evolve, legal requirements change, or our organization grows and matures. As a student-run initiative, we are continuously learning and may need to adjust our practices to reflect new insights, feedback from users and advisors, changes in applicable laws and regulations, or enhancements to our services and technology infrastructure. When we make material changes to this Privacy Policy that significantly affect how we collect, use, or protect your personal data, we will notify you through prominent notices on our website, email communications to registered users, or other appropriate channels. We will also update the "Last updated" date at the top of this policy to reflect when changes were made. We encourage you to review this Privacy Policy periodically to stay informed about how we are protecting your information. Your continued use of our services after any modifications to this policy will constitute your acknowledgment and acceptance of the updated terms.
            </p>
            <p>
              If you have any questions, concerns, suggestions, or requests regarding this Privacy Policy, our data handling practices, or your privacy rights, we welcome and encourage you to contact us. As a student organization, we value open communication and are committed to addressing your inquiries promptly and thoroughly. You can reach our team by sending an email to fewinfos@gmail.com, where our dedicated student representatives will respond to your message as quickly as possible. You may also contact us by phone at +91 8122118540 during our operating hours, though please note that as students, our availability may vary during examination periods, academic breaks, and holidays. Additionally, you can send written correspondence by mail to Karur, TN, India, and we will respond in writing to any formal requests or concerns. We appreciate your trust in FewInfos and your understanding as we work diligently to provide excellent services while pursuing our education and building valuable real-world experience in technology and business.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Privacy;
